#!/usr/bin/env python3

import sys
from rqt_gui.main import Main

plugin = '{{rqt_gui_template}}.{{rqt_gui_template}}.{{class_name}}'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

